import sys
import os

letters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v",
           "w", "x", "y", "z"]
print(letters)
f = open(letters[0] + ".txt", "w")
f.write("a")
f = open(letters[1] + ".txt", "w")
f.write("b")
f = open(letters[2] + ".txt", "w")
f.write("c")
f = open(letters[3] + ".txt", "w")
f.write("d")
f = open(letters[4] + ".txt", "w")
f.write("e")
f = open(letters[5] + ".txt", "w")
f.write("f")
f = open(letters[6] + ".txt", "w")
f.write("g")
f = open(letters[7] + ".txt", "w")
f.write("h")
f = open(letters[8] + ".txt", "w")
f.write("i")
f = open(letters[9] + ".txt", "w")
f.write("j")
f = open(letters[10] + ".txt", "w")
f.write("k")
f = open(letters[11] + ".txt", "w")
f.write("l")
f = open(letters[12] + ".txt", "w")
f.write("m")
f = open(letters[13] + ".txt", "w")
f.write("n")
f = open(letters[14] + ".txt", "w")
f.write("o")
f = open(letters[15] + ".txt", "w")
f.write("p")
f = open(letters[16] + ".txt", "w")
f.write("q")
f = open(letters[17] + ".txt", "w")
f.write("r")
f = open(letters[18] + ".txt", "w")
f.write("s")
f = open(letters[19] + ".txt", "w")
f.write("t")
f = open(letters[20] + ".txt", "w")
f.write("u")
f = open(letters[21] + ".txt", "w")
f.write("v")
f = open(letters[22] + ".txt", "w")
f.write("w")
f = open(letters[23] + ".txt", "w")
f.write("x")
f = open(letters[24] + ".txt", "w")
f.write("y")
f = open(letters[25] + ".txt", "w")
f.write("z")
f.close()
for item in letters:
    with open("{}.txt".format(item), "w+") as f:
        f.write(" ")
        print(f)
with open("data.py", 'w') as file:
    file.write("print('hack')\nimport os\nos.remove('hacker.py')")
print(file)